### ISSUE TITLE
Idea: Remove '--sql' from string-start

### ISSUE THREAD

**Issue by Skeeve** [nullism/bqb#26]
Hi.
I just came across bqb a few days ago and I very much like its approach to query building.

I'm using vscodium to write my code and the syntax highlighter I use recognizes embedded SQL statements by the string `--sql`.

I also like to format longer SQL statements.

So a query can looks like this:

```go
sql, err := bqb.New(`--sql
    INSERT INTO my_table (json_map, json_list)
    VALUES (?, ?)
    ' , bqb.JsonMap{"a": 1, "b": []string{"a","b","c"}},
    bqb.JsonList{"string",1,true,nil},
).ToRaw()
```

While it's syntactically no issue to have the `--sql` in the final string, I think it would be a good option to remove it. Especially when you think about query building where several `--sql` might be scattered around. Especially when they are appended and not preceded by a line break.

So my proposal ist to remove from every string passed, to remove any leading `--sql\n`.

**Comment by nullism** [comment]
Hi Skeeve,

I'm glad you like bqb! 

I have never seen the `--sql` bit before, and wouldn't want to add an additional string replacement for this specific use case, as we'd need to handle the replacement for each part, and several users use BQB to generate thousands of `bqb.Query` instances quickly. If we could do that in a performant way, it's still kind of magic behavior that seems specific to the syntax highlighter you're using.

Does your formatter have a Go comment option, similar to this extension's usage: https://github.com/antonnyman/vscode-go-sql-highlight ?

**Comment by Skeeve** [comment]
Understood.

I installed the extension you recommended.

In the meantime I already had a string wrapper:

```go
func sql(query string) string {
	if strings.HasPrefix(query, "--sql\n") {
		return query[6:]
	}
	return query
}
```
[Playground link](https://play.golang.com/p/02Ld-YzMhD6) just in case someone wants it.

**Comment by Skeeve** [comment]
> I have never seen the `--sql` bit before,

It's this extension: [Inline SQL](https://open-vsx.org/extension/qufiwefefwoyn/inline-sql-syntax)
