### ISSUE TITLE
Refactor SQL params replacement logic to support multiple dialects

### ISSUE THREAD

**Issue by ew3g** [nullism/bqb#32]
Hello @nullism ,
I was exploring the project and noticed an opportunity to refactor the logic of sql parameters replacement. Currently the code handles params in a single function `dialectReplace` through a switch statement, making a little harder to implement new dialects if necessary.
My proposal is to create an interface `DialectReplacer` with specific implementation for each existing dialect `Raw`, `SQL`, `MySQL` and `PgSQL`  to encapsulate the replacement logic, making the code more modular.

#### `DialectReplacer `Interface
Define the contract for any class implementing the parameter replacement logic for SQL queries.

```
type DialectReplacer interface {
    GetReplacedSQL() (string, error)
}
```

#### Modularization
Extract the replacement code into its own file (dialect_replacer.go) with dedicated tests (dialect_replacer_test.go).

#### Backward Compatibility
The current functionality remains intact without breaking the existing API while introducing a new implementation pattern.

I would like to know what you think of this approach. I've already implemented an initial version of this proposal in my fork and can send a PR with the details if you approve.

Thanks in advance for your time and for creating this amazing project.

**Comment by nullism** [comment]
Hi ew3g!

Glad you like the project and thanks for your thoughtful input!

I can see a benefit in that approach, as you say it makes it easier to implement new dialects. I do not see that code on your fork, but I imagine the usage would be something like `q.ToMySql()` would instantiate a `MySql` dialect replacer? I might not be understanding why an interface would be required here, unless a dialect replacer must be instantiated and injected to a new `To()` method or added upon query creation. If one of those cases I am opposed to that additional step when using the API. Is the presumed benefit of injecting a dialect replacer instance is the ability to extend bqb _externally_? 

If not one of those cases, then I do not understand the benefit of an interface. We could inline that logic from the switch to the specific `ToX()` methods and achieve the removal of the switch. 

I am not flatly opposed to something like this but would need to see an example of usage to understand it more fully.

**Comment by nullism** [comment]
Hey @ew3g,

I think I understand a bit better now. Thanks for the explanation!

The main question I have is: what is the problem you'd like to solve? 

Looking over the code, it seems `paramPh` is internally defined anyway, and I believe we'd need to export that to extend `bqb` externally, so a dialect replacer interface wouldn't solve for that anyway since the parameters are encoded. 

If there's a tangible use case I'd be more open to changing something so fundamental.

Thanks again!

**Comment by nullism** [comment]
Hey @ew3g,

It's my inclination to avoid changes if they don't provide some additional functionality. While I totally understand the argument that a replacer implementation might be more extensible for the future, it feels a bit like premature optimization for the sake of it to me. There'd likely be a slight performance hit when compared to a `switch` statement (heap allocation) so we'd need to (in my opinion) show some benefit for the user.

So I'm going to close this out for now, but wanted to thank you again for the interest in `bqb`!

**Comment by ew3g** [comment]
Hey @nullism ,
Sure I totally understand your point.
Thanks a lot for your time and explanations!
